Expose lib from browser field
godaddy/react-validation-context pull request #7
Opened 2018-10-10 20:34 UTC by kinetifex

2018-10-11 00:02 UTC, rxmarbles approved these changes

2018-10-11 13:24 UTC, 3rd-Eden requested changes

2018-10-11 13:24 UTC, 3rd-Eden commented on package.json
> +  "module": "./index",
We probably want to ensure that `react-native` still receives the uncompiled library, so you will end up with the following keys;

```
  "main": "./lib",
  "browser": "./lib",
  "module": "./index",
  "react-native": "./index",
```

2018-10-11 15:50 UTC, msluther approved these changes
Once @3rd-Eden 's comments are addressed.

2018-10-12 15:14 UTC, 3rd-Eden approved these changes

2018-10-12 15:14 UTC, merged

2018-10-12 15:43 UTC, 3rd-Eden commented
Published as `4.0.0`